// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKms878nkySKbSELiJfic3uGOrTFk1aI',
    appId: '1:178454095150:web:fb8d3d67924d87106206bf',
    messagingSenderId: '178454095150',
    projectId: 'autofbpost1',
    authDomain: 'autofbpost1.firebaseapp.com',
    storageBucket: 'autofbpost1.firebasestorage.app',
    measurementId: 'G-K7WEGESEWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCSc8x5Jb6JjrUBtLHn8N6Z-4xbdLfvQ',
    appId: '1:178454095150:android:3e173ed3498cc2396206bf',
    messagingSenderId: '178454095150',
    projectId: 'autofbpost1',
    storageBucket: 'autofbpost1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87oRPwyndn2PrS2Ox_QWzC5PMQLoXhEM',
    appId: '1:178454095150:ios:d65f284a245c19216206bf',
    messagingSenderId: '178454095150',
    projectId: 'autofbpost1',
    storageBucket: 'autofbpost1.firebasestorage.app',
    iosBundleId: 'com.example.autoFbPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87oRPwyndn2PrS2Ox_QWzC5PMQLoXhEM',
    appId: '1:178454095150:ios:d65f284a245c19216206bf',
    messagingSenderId: '178454095150',
    projectId: 'autofbpost1',
    storageBucket: 'autofbpost1.firebasestorage.app',
    iosBundleId: 'com.example.autoFbPost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByKms878nkySKbSELiJfic3uGOrTFk1aI',
    appId: '1:178454095150:web:3da5579f0d5acb4d6206bf',
    messagingSenderId: '178454095150',
    projectId: 'autofbpost1',
    authDomain: 'autofbpost1.firebaseapp.com',
    storageBucket: 'autofbpost1.firebasestorage.app',
    measurementId: 'G-8459FRLQ6J',
  );
}
