name: Tự động kiểm tra & đăng bài Fanpage
run-name: Kiểm tra lịch đăng bài

on:
  schedule:
    - cron: '*/5 16-23 * * *'
    - cron: '*/5 0-16 * * *'
  workflow_dispatch:

jobs:
  auto-post:
    runs-on: ubuntu-latest
    steps:
      - name: Tải mã nguồn
        uses: actions/checkout@v4

      - name: Cài Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '22'

      - name: Cài thư viện
        working-directory: ./scheduler
        run: npm install # Đổi từ npm ci thành npm install

      - name: Chạy script đăng bài
        working-directory: ./scheduler
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node run.js